import  React,{useState} from 'react';
import { styled } from '@mui/material/styles';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import CardMedia from '@mui/material/CardMedia';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import Collapse from '@mui/material/Collapse';
import Avatar from '@mui/material/Avatar';
import IconButton from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';
import { red } from '@mui/material/colors';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ShareIcon from '@mui/icons-material/Share';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Toolbar from '@mui/material/Toolbar';
import OneCard from './oneCard';
//import Typography from '@mui/material/Typography';
//import IconButton from '@mui/material/IconButton';
import Paper from '@mui/material/Paper';
import Fab from '@mui/material/Fab';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import ListSubheader from '@mui/material/ListSubheader';
import swal from 'sweetalert';
import Grid from "@mui/material/Grid";
const ExpandMore = styled((props) => {
  const { expand, ...other } = props;
  return <IconButton {...other} />;
})(({ theme, expand }) => ({
  transform: !expand ? 'rotate(0deg)' : 'rotate(180deg)',
  marginLeft: 'auto',
  transition: theme.transitions.create('transform', {
    duration: theme.transitions.duration.shortest,
  }),
}));
const StyledFab = styled(Fab)({
  position: 'absolute',
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: '0 auto',
});
const messages = [
  {
    id: 1,
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];
    
export default function PassengerFlights() {
  const [myFlights, setMyFlights] = useState([
    {
        codeFlight: 1,
        pathFlight: "טיסה פריז-ישראל"
    },
    {
        codeFlight: 2,
        pathFlight: "טיסה פריז -הודו"
    },
    {
        codeFlight: 3,
        pathFlight: "טיסה פריז -הודו"
    },
    {
        codeFlight: 4,
        pathFlight: "טיסה פריז -הודו"
    },
    {
      codeFlight: 4,
      pathFlight: "טיסה פריז -הודו"
  },
])
  const [expanded, setExpanded] = useState(false);
  const [user,setUser]=useState(localStorage.getItem(""))
  const handleExpandClick = () => {
    setExpanded(!expanded);
  };
  const chooseFriend=()=>{
   if(user.wantTogether<3)
swal({
  title: "Are you sure?",
  text: "Once deleted, you will not be able to recover this imaginary file!",
  icon: "warning",
  buttons: true,
  dangerMode: true,
  confirmButtonText: 'המשך',
})
.then((willDelete) => {
  if (willDelete) {
    swal("החבר נוסף בהצלחה לרשימה", {
      icon: "success",
    });
    setUser({...user})
    console.log("kk")
  } 

});
else
{
  swal("Good job!", 
  "לא ניתן לאשר יותר מ3 חברים!", "info");
}

   //sweet
   //עדכון בדטה בייס
  //עדכון ביוזר הנוכחי
   //else

   //sw לא ניתן יותר מ3
  }
const[passengerFly,setPassengerFly]=useState();
  return (
  <>
   <Box sx={{ flexGrow: 1, margin: '8px' }}>
        <Grid container spacing={{ xs: 2, md: 3 }}>
     {myFlights.map((item) => (
       <Grid item xs={2} sm={3} md={3} key={item.ID}>
<OneCard/>
    </Grid>
    ))}
   </Grid>
      </Box>
  
    </>
  );
}